### ISSUE TITLE
Change License file to MIT

### ISSUE THREAD

**Issue by fdlessard** [fdlessard/maven_template_app#4]
Hey Rodrigo, this Sergey dude is annoying  ! Please replace his licence file with the MIT one .

**Comment by Laesod** [comment]
If you speak to Rodrigo then use his @jordao76 alias :-1:

**Comment by jordao76** [comment]
will do shortly

**Comment by Laesod** [comment]
Nooooo, Don't revert my work :-1:

**Comment by Laesod** [comment]
@fdlessard  you should put @jordao76 to Assignees section of this ticket

**Comment by fdlessard** [comment]
Good Job @jordao76    :+1:    :8ball:
